In [ ]:
import numpy as np
from datascience import *
import random
import pandas as pd
import os 

# These lines do some fancy plotting magic
import matplotlib
%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
import warnings
warnings.simplefilter('ignore')
from datetime import datetime

In [ ]:
#generates mock distribution of ratings
def generateValue():
  r = random.random()
  if r < 0.1:
    return 1
  elif  r < 0.3:
    return 2
  elif r < 0.6:
    return 3
  elif r < 0.9:
    return 4
  else:
    return 5 

#number of reviews 
big_size = 500

ratings = make_array()
for i in range(big_size):
  ratings = np.append(ratings, generateValue())

ratings

array([ 4.,  2.,  4.,  1.,  4.,  3.,  2.,  3.,  3.,  4.,  2.,  1.,  5.,
        4.,  4.,  5.,  2.,  3.,  4.,  1.,  3.,  2.,  5.,  3.,  4.,  1.,
        4.,  3.,  3.,  3.,  3.,  4.,  2.,  3.,  5.,  2.,  4.,  1.,  2.,
        3.,  4.,  3.,  3.,  3.,  1.,  1.,  3.,  2.,  5.,  1.,  3.,  2.,
        4.,  4.,  3.,  5.,  5.,  4.,  4.,  3.,  3.,  2.,  2.,  3.,  3.,
        3.,  2.,  3.,  2.,  3.,  4.,  3.,  4.,  4.,  2.,  4.,  3.,  2.,
        2.,  1.,  2.,  4.,  3.,  2.,  4.,  3.,  4.,  2.,  5.,  4.,  2.,
        3.,  3.,  3.,  3.,  3.,  5.,  2.,  4.,  4.,  3.,  3.,  4.,  4.,
        1.,  4.,  1.,  2.,  2.,  5.,  4.,  5.,  4.,  3.,  3.,  4.,  3.,
        1.,  4.,  2.,  3.,  4.,  1.,  4.,  3.,  4.,  4.,  3.,  4.,  4.,
        4.,  2.,  4.,  1.,  4.,  3.,  1.,  3.,  2.,  4.,  3.,  4.,  3.,
        2.,  2.,  4.,  5.,  4.,  2.,  3.,  1.,  4.,  3.,  3.,  2.,  4.,
        4.,  3.,  5.,  2.,  3.,  4.,  1.,  4.,  5.,  3.,  1.,  2.,  3.,
        3.,  2.,  3.,  1.,  2.,  4.,  3.,  4.,  3.,  4.,  3.,  4

In [ ]:
reviews = Table().with_column("ratings", ratings)
reviews

ratings
4
2
4
1
4
3
2
3
3
4
... (490 rows omitted)

In [ ]:
#simulated data of importances, in full model would use real data 
importance = np.random.gumbel(150, 50, big_size)
importance

array([ 211.80632237,  244.25129782,  205.01777278,  156.48900805,
        153.7081397 ,   97.17439231,  204.97764457,  432.92768815,
        191.34470761,  135.37027942,  112.57484674,  184.39379943,
        240.00943795,  177.98410695,  244.49975771,  104.94496264,
        120.84151837,  149.79676616,  309.97970854,  138.77532161,
         51.28670242,  200.24463895,  168.51386024,   84.12843637,
        238.26760585,  163.36561609,  122.62912928,  283.81889013,
        119.5427586 ,  153.92845158,  188.51139825,  206.08564516,
        206.3206881 ,  173.74842158,  253.72671523,  103.28181502,
         70.88011281,  145.13162313,  198.91743094,  107.72864373,
        194.52378875,  285.19190571,  139.91018331,  160.50088058,
        274.97430222,  227.62511905,  151.34561436,  107.33555588,
        177.2113055 ,  216.41132605,   99.68894664,  166.00055071,
        508.73858713,  245.00524623,  350.96282656,  192.5958709 ,
        228.848564  ,  171.22528232,  111.80486824,  142.39044

In [ ]:
reviews = reviews.with_column("importance", importance)
reviews

ratings | importance
4       | 211.806
2       | 244.251
4       | 205.018
1       | 156.489
4       | 153.708
3       | 97.1744
2       | 204.978
3       | 432.928
3       | 191.345
4       | 135.37
... (490 rows omitted)

In [ ]:
#random variables are used for simulating random similarities
random_variables = np.random.random_integers(1, 2000, big_size)
reviews = reviews.with_column("random var", random_variables)

In [ ]:

random_variables
def find_similarity(var):
  diff_arr = make_array()
  for r in random_variables:
    diff_arr = np.append(diff_arr, abs(r - var))
  return 2000 - diff_arr


In [ ]:
similarity = find_similarity(11)
similarity

array([  969.,  1159.,  1428.,   378.,   304.,  1484.,  1635.,   812.,
        1963.,  1036.,   916.,  1130.,   419.,   707.,  1408.,   561.,
          66.,  1584.,   481.,   266.,  1224.,  1022.,  1509.,  1712.,
        1536.,  1976.,  1483.,   208.,   853.,  1923.,  1351.,   123.,
         683.,   847.,   140.,   448.,   230.,   241.,   294.,  1404.,
        1813.,   729.,   211.,   311.,  1827.,   817.,  1474.,  1106.,
        1637.,   705.,   741.,  1561.,  1427.,  1691.,   297.,   273.,
         876.,  1942.,  1804.,   742.,  1643.,  1228.,   242.,  1528.,
         275.,   352.,  1911.,   319.,    54.,   251.,   832.,  1549.,
        1404.,  1992.,  1460.,   840.,  1586.,  1198.,   145.,   983.,
         353.,  1495.,  1186.,   822.,   235.,   182.,   131.,  1306.,
        1931.,   358.,   420.,  1348.,   169.,   833.,    42.,  1641.,
         364.,  1947.,  1085.,  1162.,  1548.,   904.,  1920.,  1237.,
        1223.,  1519.,  1333.,  1761.,  1251.,   534.,  1593.,  1371.,
      

In [ ]:
similarities = reviews.apply(find_similarity, "random var")
reviews = reviews.with_column("similarities", similarities)
reviews

ratings | importance | random var | similarities
4       | 211.806    | 1042       | [ 2000.  1810.  1541.  1409.  1335.  1485.  1334.  1843. ...
2       | 244.251    | 852        | [ 1810.  2000.  1731.  1219.  1145.  1675.  1524.  1653. ...
4       | 205.018    | 583        | [ 1541.  1731.  2000.   950.   876.  1944.  1793.  1384. ...
1       | 156.489    | 1633       | [ 1409.  1219.   950.  2000.  1926.   894.   743.  1566. ...
4       | 153.708    | 1707       | [ 1335.  1145.   876.  1926.  2000.   820.   669.  1492. ...
3       | 97.1744    | 527        | [ 1485.  1675.  1944.   894.   820.  2000.  1849.  1328. ...
2       | 204.978    | 376        | [ 1334.  1524.  1793.   743.   669.  1849.  2000.  1177. ...
3       | 432.928    | 1199       | [ 1843.  1653.  1384.  1566.  1492.  1328.  1177.  2000. ...
3       | 191.345    | 48         | [ 1006.  1196.  1465.   415.   341.  1521.  1672.   849. ...
4       | 135.37     | 975        | [ 1933.  1877.  1608.  1342.  1268.  1552.  1401.  1776. ...
... (490 rows omitted)

In [ ]:
similarities

array([[ 2000.,  1810.,  1541., ...,  1381.,  1373.,  1729.],
       [ 1810.,  2000.,  1731., ...,  1571.,  1183.,  1919.],
       [ 1541.,  1731.,  2000., ...,  1840.,   914.,  1812.],
       ..., 
       [ 1381.,  1571.,  1840., ...,  2000.,   754.,  1652.],
       [ 1373.,  1183.,   914., ...,   754.,  2000.,  1102.],
       [ 1729.,  1919.,  1812., ...,  1652.,  1102.,  2000.]])

In [ ]:
for i in range(len(similarities)):
  for j in range(len(similarities[0])):
    if i == j:
      similarities[i][j] = 0

reviews = reviews.with_column("similarities", similarities)
reviews

ratings | importance | random var | similarities
4       | 211.806    | 1042       | [    0.  1810.  1541.  1409.  1335.  1485.  1334.  1843. ...
2       | 244.251    | 852        | [ 1810.     0.  1731.  1219.  1145.  1675.  1524.  1653. ...
4       | 205.018    | 583        | [ 1541.  1731.     0.   950.   876.  1944.  1793.  1384. ...
1       | 156.489    | 1633       | [ 1409.  1219.   950.     0.  1926.   894.   743.  1566. ...
4       | 153.708    | 1707       | [ 1335.  1145.   876.  1926.     0.   820.   669.  1492. ...
3       | 97.1744    | 527        | [ 1485.  1675.  1944.   894.   820.     0.  1849.  1328. ...
2       | 204.978    | 376        | [ 1334.  1524.  1793.   743.   669.  1849.     0.  1177. ...
3       | 432.928    | 1199       | [ 1843.  1653.  1384.  1566.  1492.  1328.  1177.     0. ...
3       | 191.345    | 48         | [ 1006.  1196.  1465.   415.   341.  1521.  1672.   849. ...
4       | 135.37     | 975        | [ 1933.  1877.  1608.  1342.  1268.  1552.  1401.  1776. ...
... (490 rows omitted)

In [ ]:
sim_sums = reviews.apply(sum, "similarities")
reviews = reviews.with_column("similarity sum", sim_sums)
reviews

ratings | importance | random var | similarities                                                 | similarity sum
4       | 211.806    | 1042       | [    0.  1810.  1541.  1409.  1335.  1485.  1334.  1843. ... | 749091
2       | 244.251    | 852        | [ 1810.     0.  1731.  1219.  1145.  1675.  1524.  1653. ... | 750415
4       | 205.018    | 583        | [ 1541.  1731.     0.   950.   876.  1944.  1793.  1384. ... | 721467
1       | 156.489    | 1633       | [ 1409.  1219.   950.     0.  1926.   894.   743.  1566. ... | 634967
4       | 153.708    | 1707       | [ 1335.  1145.   876.  1926.     0.   820.   669.  1492. ... | 609927
3       | 97.1744    | 527        | [ 1485.  1675.  1944.   894.   820.     0.  1849.  1328. ... | 710185
2       | 204.978    | 376        | [ 1334.  1524.  1793.   743.   669.  1849.     0.  1177. ... | 667959
3       | 432.928    | 1199       | [ 1843.  1653.  1384.  1566.  1492.  1328.  1177.     0. ... | 735241
3       | 191.345    | 48         | [ 1006.  1196.  1465.   415.   341.  1521.  1672.   849. ... | 537941
4       | 135.37     | 975        | [ 1933.  1877.  1608.  1342.  1268.  1552.  1401.  1776. ... | 751733
... (490 rows omitted)

In [ ]:
def find_proportion(similarities, total_sum):
  return similarities / total_sum

similarity_proportions = reviews.apply(find_proportion, "similarities", "similarity sum")
similarity_proportions

array([[ 0.        ,  0.00241626,  0.00205716, ...,  0.00184357,
         0.00183289,  0.00230813],
       [ 0.002412  ,  0.        ,  0.00230672, ...,  0.00209351,
         0.00157646,  0.00255725],
       [ 0.00213593,  0.00239928,  0.        , ...,  0.00255036,
         0.00126686,  0.00251155],
       ..., 
       [ 0.00202284,  0.00230115,  0.00269517, ...,  0.        ,
         0.00110443,  0.00241979],
       [ 0.00220351,  0.00189858,  0.00146687, ...,  0.00121008,
         0.        ,  0.00176858],
       [ 0.00231903,  0.00257387,  0.00243035, ...,  0.00221575,
         0.00147806,  0.        ]])

In [ ]:
for i in range(len(similarity_proportions)):
  for j in range(len(similarity_proportions)):
    if i == j:
      similarity_proportions[i][j] = 0.9
    else:
      similarity_proportions[i][j] = similarity_proportions[i][j] * 0.1

reviews = reviews.with_column("similarity proportions", similarity_proportions)
reviews

ratings | importance | random var | similarities                                                 | similarity sum | similarity proportions
4       | 211.806    | 1042       | [    0.  1810.  1541.  1409.  1335.  1485.  1334.  1843. ... | 749091         | [  9.00000000e-01   2.41626184e-04   2.05715994e-04   1. ...
2       | 244.251    | 852        | [ 1810.     0.  1731.  1219.  1145.  1675.  1524.  1653. ... | 750415         | [  2.41199869e-04   9.00000000e-01   2.30672361e-04   1. ...
4       | 205.018    | 583        | [ 1541.  1731.     0.   950.   876.  1944.  1793.  1384. ... | 721467         | [  2.13592583e-04   2.39927814e-04   9.00000000e-01   1. ...
1       | 156.489    | 1633       | [ 1409.  1219.   950.     0.  1926.   894.   743.  1566. ... | 634967         | [  2.21901296e-04   1.91978481e-04   1.49614074e-04   9. ...
4       | 153.708    | 1707       | [ 1335.  1145.   876.  1926.     0.   820.   669.  1492. ... | 609927         | [  2.18878653e-04   1.87727384e-04   1.43623745e-04   3. ...
3       | 97.1744    | 527        | [ 1485.  1675.  1944.   894.   820.     0.  1849.  1328. ... | 710185         | [  2.09100446e-04   2.35854038e-04   2.73731492e-04   1. ...
2       | 204.978    | 376        | [ 1334.  1524.  1793.   743.   669.  1849.     0.  1177. ... | 667959         | [  1.99712857e-04   2.28157716e-04   2.68429649e-04   1. ...
3       | 432.928    | 1199       | [ 1843.  1653.  1384.  1566.  1492.  1328.  1177.     0. ... | 735241         | [  2.50666108e-04   2.24824241e-04   1.88237598e-04   2. ...
3       | 191.345    | 48         | [ 1006.  1196.  1465.   415.   341.  1521.  1672.   849. ... | 537941         | [  1.87009356e-04   2.22329215e-04   2.72334698e-04   7. ...
4       | 135.37     | 975        | [ 1933.  1877.  1608.  1342.  1268.  1552.  1401.  1776. ... | 751733         | [  2.57139170e-04   2.49689717e-04   2.13905735e-04   1. ...
... (490 rows omitted)

In [ ]:
matriixx = np.asmatrix(similarity_proportions)
matriixx

matrix([[  9.00000000e-01,   2.41626184e-04,   2.05715994e-04, ...,
           1.84356774e-04,   1.83288813e-04,   2.30813079e-04],
        [  2.41199869e-04,   9.00000000e-01,   2.30672361e-04, ...,
           2.09350826e-04,   1.57646102e-04,   2.55725165e-04],
        [  2.13592583e-04,   2.39927814e-04,   9.00000000e-01, ...,
           2.55035920e-04,   1.26686321e-04,   2.51154938e-04],
        ..., 
        [  2.02284156e-04,   2.30114706e-04,   2.69516906e-04, ...,
           9.00000000e-01,   1.10443341e-04,   2.41979309e-04],
        [  2.20350924e-04,   1.89858080e-04,   1.46686631e-04, ...,
           1.21008447e-04,   9.00000000e-01,   1.76858499e-04],
        [  2.31902797e-04,   2.57386620e-04,   2.43035204e-04, ...,
           2.21575142e-04,   1.47806178e-04,   9.00000000e-01]])

In [ ]:
importance

array([ 211.80632237,  244.25129782,  205.01777278,  156.48900805,
        153.7081397 ,   97.17439231,  204.97764457,  432.92768815,
        191.34470761,  135.37027942,  112.57484674,  184.39379943,
        240.00943795,  177.98410695,  244.49975771,  104.94496264,
        120.84151837,  149.79676616,  309.97970854,  138.77532161,
         51.28670242,  200.24463895,  168.51386024,   84.12843637,
        238.26760585,  163.36561609,  122.62912928,  283.81889013,
        119.5427586 ,  153.92845158,  188.51139825,  206.08564516,
        206.3206881 ,  173.74842158,  253.72671523,  103.28181502,
         70.88011281,  145.13162313,  198.91743094,  107.72864373,
        194.52378875,  285.19190571,  139.91018331,  160.50088058,
        274.97430222,  227.62511905,  151.34561436,  107.33555588,
        177.2113055 ,  216.41132605,   99.68894664,  166.00055071,
        508.73858713,  245.00524623,  350.96282656,  192.5958709 ,
        228.848564  ,  171.22528232,  111.80486824,  142.39044

In [ ]:
new_importance = np.array(np.dot(importance, matriixx))
for i in range(500):
  new_importance = np.array(np.dot(new_importance, matriixx))
new_importance
  

array([[ 198.39646154,  198.74712243,  191.08025583,  168.17076429,
         161.53892998,  188.09222249,  176.90868273,  194.7282944 ,
         142.47346573,  199.09619422,  197.49014617,  199.03104122,
         171.55183446,  190.36251338,  192.01146707,  181.76072764,
         134.65987245,  181.13303406,  176.21848464,  157.8961884 ,
         197.78836683,  198.99767016,  186.59052519,  170.03212738,
         184.78372113,  140.82133385,  188.15048941,  151.76121196,
         196.01228533,  147.40390613,  194.27910946,  141.79015373,
         189.10024012,  195.84172217,  143.8671044 ,  173.79564038,
         154.16551675,  155.33350355,  160.59977325,  192.18626781,
         159.93447103,  191.38483288,  152.09651158,  162.19151943,
         158.42059064,  194.89991695,  188.66482736,  199.14863444,
         176.73811958,  190.26187053,  191.9245964 ,  182.91706105,
         191.12845846,  171.97400474,  160.88263264,  158.5858568 ,
         196.62038004,  145.10024419,  160.88687

In [ ]:
final_tbl = reviews.select("ratings", "importance")
final_tbl = final_tbl.with_column("steady importance",new_importance[0])
final_tbl

ratings | importance | steady importance
4       | 211.806    | 198.396
2       | 244.251    | 198.747
4       | 205.018    | 191.08
1       | 156.489    | 168.171
4       | 153.708    | 161.539
3       | 97.1744    | 188.092
2       | 204.978    | 176.909
3       | 432.928    | 194.728
3       | 191.345    | 142.473
4       | 135.37     | 199.096
... (490 rows omitted)

In [ ]:
total_importance = sum(final_tbl.column("steady importance"))
proportional_importance = final_tbl.column("steady importance") / total_importance
proportional_importance
final_tbl = final_tbl.with_column("proportional importance", proportional_importance)
final_tbl
cool_average = sum(final_tbl.column("ratings") * final_tbl.column("proportional importance"))
cool_average

3.0834469114389957

In [ ]:
vanilla_average_rating = np.mean(final_tbl.column("ratings"))
vanilla_average_rating

3.0800000000000001

In [ ]:
final_tbl

ratings | importance | steady importance | proportional importance
4       | 211.806    | 198.396           | 0.00223432
2       | 244.251    | 198.747           | 0.00223827
4       | 205.018    | 191.08            | 0.00215193
1       | 156.489    | 168.171           | 0.00189392
4       | 153.708    | 161.539           | 0.00181924
3       | 97.1744    | 188.092           | 0.00211828
2       | 204.978    | 176.909           | 0.00199233
3       | 432.928    | 194.728           | 0.00219301
3       | 191.345    | 142.473           | 0.00160452
4       | 135.37     | 199.096           | 0.0022422
... (490 rows omitted)

In [ ]:
os.system("touch results.csv")
final_tbl.to_csv('results.csv')